# # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Content: docker compose for graylog
# Author: Jan Jambor
# Author URI: https://xwr.ch
# Date: 25.03.2020
#
# # # # # # # # # # # # # # # # # # # # # # # # # #

version: "2"

services:

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:3
    restart: always
    volumes:
      - '/share/Container/graylog/mongodb/:/data/db/'
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: 'udp://graylog:12201'
    networks:
      2rockLAN:
        ipv4_address: 192.168.100.32

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:6.8.7
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      # - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - '/share/Container/graylog/elasticsearch/:/usr/share/elasticsearch/data/'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: 'udp://graylog:12201'
    networks:
      2rockLAN:
        ipv4_address: 192.168.100.31

  graylog:
    container_name: graylog
    hostname: graylog
    image: graylog/graylog:3.2.4-1
    restart: always
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=
      # Password for admin: echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.your.domain/
      - GRAYLOG_HTTP_PUBLISH_URI=https://graylog.your.domain/
    volumes:
      - '/share/Container/graylog/graylog/:/usr/share/graylog/data/journal/'
      - '/share/Container/lets-encrypt/conf/:/usr/share/graylog/letsencrypt/' # let's encrypt cerst
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 31080:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # RawText TCP
      - 5555:5555
      # RawText TCP
      - 5044:5044
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: 'udp://graylog:12201'
    networks:
      2rockLAN:
        ipv4_address: 192.168.100.30

networks:
  2rockLAN:
    external:
      name: qnet-static-bond0-076754
