# # # # # # # # # # # # # # #
# Due to bug in ansible, get the fixed component before ansible gets the update
# https://github.com/ansible-collections/community.general/pull/1038#issuecomment-719538134
#
# $ ansible-galaxy collection install -r roles/requirements.yml
#
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
    version: 1.3.7 
