---
# # # #
# donwloaded sw paackage is installed
# 
# a terms of service popup will occure
# 
- name: install {{ appname }}
  become: yes
  become_method: sudo
  become_user: root
  shell: installer -store -pkg "{{ swrepopath }}/tiptoi_Manager_Installer.pkg" -target /
