#!/usr/bin/env ansible-playbook

- hosts: jjsmbp
  connection: local
  vars_prompt:
  - name: ansible_become_user
    prompt: admin user
  - name: ansible_become_pass
    prompt: admin password
  roles:
  - maintenance # performe some maintenance tasks first
  - homebrew # updates also existing apps
  - aks
  - calibre
  - dotnet
  - firefox
  - forklift
  - gimp
  - git
  - inkscape
  - iterm2
  - keepassxc
  - licecap
  - mas
  - microsoft-azure-storage-explorer
  - microsoft-teams
  - postman
  - signal
  - qsync-client
  - skype
  - sox # quick tipp: find . -name '*.flac' -type f -exec bash -c 'echo "$1" && sox "$1" -C 320 "${1/flac/mp3}" && rm "$1"' -- {} \;
  - talisman
  - teamviewer
  - terraform
  #- tiptoy
  - tor-browser
  - twitterrific
  - visual-studio-code # workaround in place, see roles/requirements.yml and https://github.com/ansible-collections/community.general/issues/1037 # required plugins: hashicorp.terraform and more ...
  - zoom

  # move log to a file with date and time to keep it for future reference
  - post-processing

## Apps to add:
# brew install --cask tunnelblick

## Apps to check (really required?)
# brew install --cask adobe-acrobat-reader
# brew install --cask keyboard-maestro
# brew install krew # add to nano ~/.zshrc >> export PATH="${PATH}:${HOME}/.krew/bin"
# brew install kubernetes-cli # >> remove the one from aks
# brew install detox # clearing filenames 
# brew install --cask plex
# brew install --cask docker
# brew install jq
# DxO Setup
