# # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Content: basis for further apps
# Author: Jan Jambor, XWare GmbH
# Author URI: https://xwr.ch
# Date: 02.01.2021
#
# - before running this, check:
#   - Line 38 / 39: azurestorageaccountname & azurestorageaccountkey
#
# # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # #
# Namespace
# kubectl config set-context --current --namespace=ns-apps
apiVersion: v1
kind: Namespace
metadata:
  name: ns-apps
---
# # # # # # # # # # # # # # #
# secret for azure file storage
# echo -n 'azurestorageaccountname' | base64
# echo -n 'azurestorageaccountkey' | base64
apiVersion: v1
kind: Secret
metadata:
  name: sec-apps-files
  namespace: ns-apps
  labels:
    environment: test
    owner: jan.jambor-at-xwr.ch
    applicationname: div
    costcenter: jj
    dr: essential
type: Opaque
data:
  azurestorageaccountname: azurestorageaccountname
  azurestorageaccountkey: azurestorageaccountkey
---
# # # # # # # # # # # # # # #
# secret for azure vault
# $ echo -n '$AZURE_CLIENT_ID' | base64
# $ echo -n '$AZURE_CLIENT_SECRET' | base64
apiVersion: v1
kind: Secret
metadata:
  name: kv-k8s-apps-vault-store-creds
  namespace: ns-apps
  labels:
    environment: test
    owner: jan.jambor-at-xwr.ch
    applicationname: div
    costcenter: jj
    dr: essential
type: Opaque
data:
  clientid: clientid
  clientsecret: clientsecret
---
# # # # # # # # # # # # # # # # # # # # # # # # # #
# Middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mw-headers
  namespace: ns-apps
spec:
  headers:
    sslRedirect: true
    sslProxyHeaders:
      X-Forwarded-Proto: "https"
