---
- name: installs {{ homebrew_formulae }} with Homebrew Cask
  homebrew_cask:
    name: "{{ homebrew_formulae }}"

# # # #
# apply settings via shell
# System restart required for this to take effect
# source: https://binarynights.com/manual#fileviewer
- name: apply settings for {{ homebrew_formulae }}
  shell: defaults write -g NSFileViewer -string com.binarynights.ForkLift-3 && defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{LSHandlerContentType="public.folder";LSHandlerRoleAll="com.binarynights.ForkLift-3";}'
